/* 
 * API for MyQ Devices
 *
 * This is a reverse engineered and incomplete version of the MyQ API.
 *
 * The version of the OpenAPI document: 5.1
 * Contact: geregam@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using spydersoft.myq.Client;
using spydersoft.myq.Model;

namespace spydersoft.myq.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieve the Account by the ID
        /// </summary>
        /// <remarks>
        /// Retrieve the Account by ID 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Account</returns>
        Account GetAccountById (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));

        /// <summary>
        /// Retrieve the Account by the ID
        /// </summary>
        /// <remarks>
        /// Retrieve the Account by ID 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>ApiResponse of Account</returns>
        ApiResponse<Account> GetAccountByIdWithHttpInfo (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));
        /// <summary>
        /// retrieve a list of accounts for the current user
        /// </summary>
        /// <remarks>
        /// Retrieve a list of accounts for the current user 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>AccountsResponse</returns>
        AccountsResponse GetAccounts (string apiVersion, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));

        /// <summary>
        /// retrieve a list of accounts for the current user
        /// </summary>
        /// <remarks>
        /// Retrieve a list of accounts for the current user 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>ApiResponse of AccountsResponse</returns>
        ApiResponse<AccountsResponse> GetAccountsWithHttpInfo (string apiVersion, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));
        /// <summary>
        /// Retrieve the Devices for a specific account
        /// </summary>
        /// <remarks>
        /// Retrieve the Devices for a specific account 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>DevicesResponse</returns>
        DevicesResponse GetDevicesByAccountId (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));

        /// <summary>
        /// Retrieve the Devices for a specific account
        /// </summary>
        /// <remarks>
        /// Retrieve the Devices for a specific account 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>ApiResponse of DevicesResponse</returns>
        ApiResponse<DevicesResponse> GetDevicesByAccountIdWithHttpInfo (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Retrieve the Account by the ID
        /// </summary>
        /// <remarks>
        /// Retrieve the Account by ID 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of Account</returns>
        System.Threading.Tasks.Task<Account> GetAccountByIdAsync (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));

        /// <summary>
        /// Retrieve the Account by the ID
        /// </summary>
        /// <remarks>
        /// Retrieve the Account by ID 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of ApiResponse (Account)</returns>
        System.Threading.Tasks.Task<ApiResponse<Account>> GetAccountByIdAsyncWithHttpInfo (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));
        /// <summary>
        /// retrieve a list of accounts for the current user
        /// </summary>
        /// <remarks>
        /// Retrieve a list of accounts for the current user 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of AccountsResponse</returns>
        System.Threading.Tasks.Task<AccountsResponse> GetAccountsAsync (string apiVersion, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));

        /// <summary>
        /// retrieve a list of accounts for the current user
        /// </summary>
        /// <remarks>
        /// Retrieve a list of accounts for the current user 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of ApiResponse (AccountsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AccountsResponse>> GetAccountsAsyncWithHttpInfo (string apiVersion, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));
        /// <summary>
        /// Retrieve the Devices for a specific account
        /// </summary>
        /// <remarks>
        /// Retrieve the Devices for a specific account 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of DevicesResponse</returns>
        System.Threading.Tasks.Task<DevicesResponse> GetDevicesByAccountIdAsync (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));

        /// <summary>
        /// Retrieve the Devices for a specific account
        /// </summary>
        /// <remarks>
        /// Retrieve the Devices for a specific account 
        /// </remarks>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of ApiResponse (DevicesResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DevicesResponse>> GetDevicesByAccountIdAsyncWithHttpInfo (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApi : IAccountApiSync, IAccountApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AccountApi : IAccountApi
    {
        private spydersoft.myq.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountApi(String basePath)
        {
            this.Configuration = spydersoft.myq.Client.Configuration.MergeConfigurations(
                spydersoft.myq.Client.GlobalConfiguration.Instance,
                new spydersoft.myq.Client.Configuration { BasePath = basePath }
            );
            this.Client = new spydersoft.myq.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new spydersoft.myq.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = spydersoft.myq.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AccountApi(spydersoft.myq.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = spydersoft.myq.Client.Configuration.MergeConfigurations(
                spydersoft.myq.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new spydersoft.myq.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new spydersoft.myq.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = spydersoft.myq.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AccountApi(spydersoft.myq.Client.ISynchronousClient client,spydersoft.myq.Client.IAsynchronousClient asyncClient, spydersoft.myq.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = spydersoft.myq.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public spydersoft.myq.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public spydersoft.myq.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public spydersoft.myq.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public spydersoft.myq.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Retrieve the Account by the ID Retrieve the Account by ID 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Account</returns>
        public Account GetAccountById (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
             spydersoft.myq.Client.ApiResponse<Account> localVarResponse = GetAccountByIdWithHttpInfo(apiVersion, id, myQApplicationId, brandId, culture, securityToken);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the Account by the ID Retrieve the Account by ID 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>ApiResponse of Account</returns>
        public spydersoft.myq.Client.ApiResponse< Account > GetAccountByIdWithHttpInfo (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new spydersoft.myq.Client.ApiException(400, "Missing required parameter 'apiVersion' when calling AccountApi->GetAccountById");

            // verify the required parameter 'id' is set
            if (id == null)
                throw new spydersoft.myq.Client.ApiException(400, "Missing required parameter 'id' when calling AccountApi->GetAccountById");

            spydersoft.myq.Client.RequestOptions localVarRequestOptions = new spydersoft.myq.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spydersoft.myq.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spydersoft.myq.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("apiVersion", spydersoft.myq.Client.ClientUtils.ParameterToString(apiVersion)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", spydersoft.myq.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (myQApplicationId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("MyQApplicationId", spydersoft.myq.Client.ClientUtils.ParameterToString(myQApplicationId)); // header parameter
            }
            if (brandId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("BrandId", spydersoft.myq.Client.ClientUtils.ParameterToString(brandId)); // header parameter
            }
            if (culture != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Culture", spydersoft.myq.Client.ClientUtils.ParameterToString(culture)); // header parameter
            }
            if (securityToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("SecurityToken", spydersoft.myq.Client.ClientUtils.ParameterToString(securityToken)); // header parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get< Account >("/{apiVersion}/Accounts/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccountById", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve the Account by the ID Retrieve the Account by ID 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of Account</returns>
        public async System.Threading.Tasks.Task<Account> GetAccountByIdAsync (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
             spydersoft.myq.Client.ApiResponse<Account> localVarResponse = await GetAccountByIdAsyncWithHttpInfo(apiVersion, id, myQApplicationId, brandId, culture, securityToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve the Account by the ID Retrieve the Account by ID 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of ApiResponse (Account)</returns>
        public async System.Threading.Tasks.Task<spydersoft.myq.Client.ApiResponse<Account>> GetAccountByIdAsyncWithHttpInfo (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new spydersoft.myq.Client.ApiException(400, "Missing required parameter 'apiVersion' when calling AccountApi->GetAccountById");

            // verify the required parameter 'id' is set
            if (id == null)
                throw new spydersoft.myq.Client.ApiException(400, "Missing required parameter 'id' when calling AccountApi->GetAccountById");


            spydersoft.myq.Client.RequestOptions localVarRequestOptions = new spydersoft.myq.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("apiVersion", spydersoft.myq.Client.ClientUtils.ParameterToString(apiVersion)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", spydersoft.myq.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (myQApplicationId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("MyQApplicationId", spydersoft.myq.Client.ClientUtils.ParameterToString(myQApplicationId)); // header parameter
            }
            if (brandId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("BrandId", spydersoft.myq.Client.ClientUtils.ParameterToString(brandId)); // header parameter
            }
            if (culture != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Culture", spydersoft.myq.Client.ClientUtils.ParameterToString(culture)); // header parameter
            }
            if (securityToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("SecurityToken", spydersoft.myq.Client.ClientUtils.ParameterToString(securityToken)); // header parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Account>("/{apiVersion}/Accounts/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccountById", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// retrieve a list of accounts for the current user Retrieve a list of accounts for the current user 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>AccountsResponse</returns>
        public AccountsResponse GetAccounts (string apiVersion, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
             spydersoft.myq.Client.ApiResponse<AccountsResponse> localVarResponse = GetAccountsWithHttpInfo(apiVersion, myQApplicationId, brandId, culture, securityToken);
             return localVarResponse.Data;
        }

        /// <summary>
        /// retrieve a list of accounts for the current user Retrieve a list of accounts for the current user 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>ApiResponse of AccountsResponse</returns>
        public spydersoft.myq.Client.ApiResponse< AccountsResponse > GetAccountsWithHttpInfo (string apiVersion, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new spydersoft.myq.Client.ApiException(400, "Missing required parameter 'apiVersion' when calling AccountApi->GetAccounts");

            spydersoft.myq.Client.RequestOptions localVarRequestOptions = new spydersoft.myq.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spydersoft.myq.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spydersoft.myq.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("apiVersion", spydersoft.myq.Client.ClientUtils.ParameterToString(apiVersion)); // path parameter
            if (myQApplicationId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("MyQApplicationId", spydersoft.myq.Client.ClientUtils.ParameterToString(myQApplicationId)); // header parameter
            }
            if (brandId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("BrandId", spydersoft.myq.Client.ClientUtils.ParameterToString(brandId)); // header parameter
            }
            if (culture != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Culture", spydersoft.myq.Client.ClientUtils.ParameterToString(culture)); // header parameter
            }
            if (securityToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("SecurityToken", spydersoft.myq.Client.ClientUtils.ParameterToString(securityToken)); // header parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get< AccountsResponse >("/{apiVersion}/Accounts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccounts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// retrieve a list of accounts for the current user Retrieve a list of accounts for the current user 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of AccountsResponse</returns>
        public async System.Threading.Tasks.Task<AccountsResponse> GetAccountsAsync (string apiVersion, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
             spydersoft.myq.Client.ApiResponse<AccountsResponse> localVarResponse = await GetAccountsAsyncWithHttpInfo(apiVersion, myQApplicationId, brandId, culture, securityToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// retrieve a list of accounts for the current user Retrieve a list of accounts for the current user 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of ApiResponse (AccountsResponse)</returns>
        public async System.Threading.Tasks.Task<spydersoft.myq.Client.ApiResponse<AccountsResponse>> GetAccountsAsyncWithHttpInfo (string apiVersion, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new spydersoft.myq.Client.ApiException(400, "Missing required parameter 'apiVersion' when calling AccountApi->GetAccounts");


            spydersoft.myq.Client.RequestOptions localVarRequestOptions = new spydersoft.myq.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("apiVersion", spydersoft.myq.Client.ClientUtils.ParameterToString(apiVersion)); // path parameter
            if (myQApplicationId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("MyQApplicationId", spydersoft.myq.Client.ClientUtils.ParameterToString(myQApplicationId)); // header parameter
            }
            if (brandId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("BrandId", spydersoft.myq.Client.ClientUtils.ParameterToString(brandId)); // header parameter
            }
            if (culture != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Culture", spydersoft.myq.Client.ClientUtils.ParameterToString(culture)); // header parameter
            }
            if (securityToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("SecurityToken", spydersoft.myq.Client.ClientUtils.ParameterToString(securityToken)); // header parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<AccountsResponse>("/{apiVersion}/Accounts", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccounts", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve the Devices for a specific account Retrieve the Devices for a specific account 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>DevicesResponse</returns>
        public DevicesResponse GetDevicesByAccountId (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
             spydersoft.myq.Client.ApiResponse<DevicesResponse> localVarResponse = GetDevicesByAccountIdWithHttpInfo(apiVersion, id, myQApplicationId, brandId, culture, securityToken);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the Devices for a specific account Retrieve the Devices for a specific account 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>ApiResponse of DevicesResponse</returns>
        public spydersoft.myq.Client.ApiResponse< DevicesResponse > GetDevicesByAccountIdWithHttpInfo (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new spydersoft.myq.Client.ApiException(400, "Missing required parameter 'apiVersion' when calling AccountApi->GetDevicesByAccountId");

            // verify the required parameter 'id' is set
            if (id == null)
                throw new spydersoft.myq.Client.ApiException(400, "Missing required parameter 'id' when calling AccountApi->GetDevicesByAccountId");

            spydersoft.myq.Client.RequestOptions localVarRequestOptions = new spydersoft.myq.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = spydersoft.myq.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = spydersoft.myq.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("apiVersion", spydersoft.myq.Client.ClientUtils.ParameterToString(apiVersion)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", spydersoft.myq.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (myQApplicationId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("MyQApplicationId", spydersoft.myq.Client.ClientUtils.ParameterToString(myQApplicationId)); // header parameter
            }
            if (brandId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("BrandId", spydersoft.myq.Client.ClientUtils.ParameterToString(brandId)); // header parameter
            }
            if (culture != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Culture", spydersoft.myq.Client.ClientUtils.ParameterToString(culture)); // header parameter
            }
            if (securityToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("SecurityToken", spydersoft.myq.Client.ClientUtils.ParameterToString(securityToken)); // header parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get< DevicesResponse >("/{apiVersion}/Accounts/{id}/Devices", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDevicesByAccountId", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve the Devices for a specific account Retrieve the Devices for a specific account 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of DevicesResponse</returns>
        public async System.Threading.Tasks.Task<DevicesResponse> GetDevicesByAccountIdAsync (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
             spydersoft.myq.Client.ApiResponse<DevicesResponse> localVarResponse = await GetDevicesByAccountIdAsyncWithHttpInfo(apiVersion, id, myQApplicationId, brandId, culture, securityToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve the Devices for a specific account Retrieve the Devices for a specific account 
        /// </summary>
        /// <exception cref="spydersoft.myq.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion">For right now, this should be v5 except for the Accounts/{id}/Devices, which is v5.1 </param>
        /// <param name="id">The ID of the account to retrieve</param>
        /// <param name="myQApplicationId"> (optional, default to &quot;JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu&quot;)</param>
        /// <param name="brandId"> (optional, default to &quot;2&quot;)</param>
        /// <param name="culture"> (optional, default to &quot;en&quot;)</param>
        /// <param name="securityToken"> (optional)</param>
        /// <returns>Task of ApiResponse (DevicesResponse)</returns>
        public async System.Threading.Tasks.Task<spydersoft.myq.Client.ApiResponse<DevicesResponse>> GetDevicesByAccountIdAsyncWithHttpInfo (string apiVersion, string id, string myQApplicationId = default(string), string brandId = default(string), string culture = default(string), string securityToken = default(string))
        {
            // verify the required parameter 'apiVersion' is set
            if (apiVersion == null)
                throw new spydersoft.myq.Client.ApiException(400, "Missing required parameter 'apiVersion' when calling AccountApi->GetDevicesByAccountId");

            // verify the required parameter 'id' is set
            if (id == null)
                throw new spydersoft.myq.Client.ApiException(400, "Missing required parameter 'id' when calling AccountApi->GetDevicesByAccountId");


            spydersoft.myq.Client.RequestOptions localVarRequestOptions = new spydersoft.myq.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("apiVersion", spydersoft.myq.Client.ClientUtils.ParameterToString(apiVersion)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", spydersoft.myq.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (myQApplicationId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("MyQApplicationId", spydersoft.myq.Client.ClientUtils.ParameterToString(myQApplicationId)); // header parameter
            }
            if (brandId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("BrandId", spydersoft.myq.Client.ClientUtils.ParameterToString(brandId)); // header parameter
            }
            if (culture != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Culture", spydersoft.myq.Client.ClientUtils.ParameterToString(culture)); // header parameter
            }
            if (securityToken != null)
            {
                localVarRequestOptions.HeaderParameters.Add("SecurityToken", spydersoft.myq.Client.ClientUtils.ParameterToString(securityToken)); // header parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DevicesResponse>("/{apiVersion}/Accounts/{id}/Devices", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDevicesByAccountId", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
